### PR TITLE
Fixes usage of options{} in SQLite move

### PR DESCRIPTION
**Pull request by sudheesh001**
This fixes the `null` usage instead of `options`. I never knew we could use them as `null`, learning +1 for the day.

### CODE REVIEW

**Comment by sudheesh001** [comment]
Commit `4c947f2` fixes part of the issue #14

**Comment by debloper** [comment]
Has conflicts man, please pull, squash rebase, push :8ball:

**Comment by sudheesh001** [comment]
Good to merge Deb :+1: Wrote a nodejs script to list out the packages for package.json, do i push that too ? @debloper

**Comment by debloper** [comment]
Dude... you need to remove the reference to ga.js as well from `app/index.html:L66`
No, just create a gist from that script, merging in-repo isn't necessary.

**Comment by sudheesh001** [comment]
Now ?

**Comment by debloper** [comment]
Awesome, merged! :D

**Pull request merged**
