### PR TITLE
Implements multiple filter in the input boxes for loading the sprint

### PR DESCRIPTION
**Pull request by sudheesh001**
- Enhancement
- Implements a CSV Filter on the input boxes to override original AngularJS filter functionality of single value.
- Supports multiple values to be filtered.

Signed off by: <ssingana@redhat.com>

### CODE REVIEW

**Comment by debloper** [comment]
Wrong branching again man... this one regresses the google-font thingy again.

**Comment by sudheesh001** [comment]
Rebased. My bad. :sweat_smile:

**Comment by debloper** [comment]
I'm gonna give this one a try tonight to check everything performs okay before I merge.
Let's keep the fingers crossed!

**Comment by debloper** [comment]
Thanks @sudheesh001, this seemed to be working, hence have merged it.
However, the fistering is noticeably slow & there might be a better way: #37

Also, feel free to open new issues & send PRs for:
- Space-separated filters instead of commas
- Auto-complition or listing of available options for filters (the prospect of it)

**Pull request merged**
