### PR TITLE
Integrates automated testing with nightwatch js

### LINKED ISSUE #40: Write integration tests for the app, to ensure no cross-module regression
Automated: http://nightwatchjs.org/
Manual: https://theintern.github.io/
Some more info to get started: http://www.supraliminalsolutions.com/blog/listings/writing-integration-tests-node-js/

### PR DESCRIPTION
**Pull request by sudheesh001**
- Tests the DB insert procedure
- Tests app on load
- Uses nightwatch.js for automated browser testing of the application
  Tries to fix #40 especially with the DB Insert because this is the page that mostly breaks on heavy changes.

Signed off by: Sudheesh Singanamalla ssingana@redhat.com

### CODE REVIEW

**Comment by debloper** [comment]
- Remove `grunt` command from YML scripts (that's what makingthe builds fail)
- Add `grunt test` instead, or better: `test` script in `package.json` (travis' defualt)
- Maybe install nightwatch globally & just do `nightwatch --test tests/appload-test.js`
- Better to have a `tests/index.js` as the bootstrapper for the tests, which calls others

**Comment by sudheesh001** [comment]
@debloper Hopefully `48f8cc2` fixes it all

**Comment by sudheesh001** [comment]
Travis says
```
Running:  Sprint App Load 
Connection refused! Is selenium server started?
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

Trying to do something to fix that,  let me try rebasing.

**Comment by debloper** [comment]
Any update on this one?

**Comment by sudheesh001** [comment]
Couldn't figure out a test with Mocha and angular, Need help on this one.

**Pull request closed without merging**
